sqlite3> INSERT INTO bears (name) VALUES ('Mr. Chocolate')
sqlite3> INSERT INTO bears (name) VALUES ('Rowdy')
sqlite3> INSERT INTO bears (name) VALUES ('Tabitha')
sqlite3> INSERT INTO bears (name) VALUES ('Sergeant Brown')
sqlite3> INSERT INTO bears (name) VALUES ('Melissa')
sqlite3> INSERT INTO bears (name) VALUES ('Grinch')
sqlite3> INSERT INTO bears (name) VALUES ('Wendy')
